### PR TITLE
Alternate rewording of ICE failure discussion

### PR DESCRIPTION
**Pull request by juberti**
Fixes #12

### CODE REVIEW

**Review by cdh4u — CHANGES_REQUESTED** [review]
I am ok with the change, but I would still want the text to say:

"if all pairs associated with one or more check lists have failed,"

It's just adding a few words :)

**Comment by juberti** [comment]
It's a lot of words, makes the sentence harder to read, and given that this is introductory text, doesn't really clarify the document. I also think we'd have to similarly rewrite several other paragraphs in the intro if we did this, so I'm not in favor of adding the suggested text.

**Comment by cdh4u** [comment]
> It's a lot of words, makes the sentence harder to read, and given that this is introductory text, doesn't >really clarify the document. I also think we'd have to similarly rewrite several other paragraphs in the >intro if we did this, so I'm not in favor of adding the suggested text.

Perhaps, there are a few places that talks about "all pairs", without clarifying that it is for a checklist.

So, at the moment, one could read the Introduction saying that ICE failure is typically declared once all pairs associated with the whole session have failed, which is not true. I assume you agree with that?

As you have indicated yourself, ICE failure can be declared when all pairs associated with ONE checklist have failed, even if there are other checklists in the Completed state.

Anyway, I think my issue is clarified in the "Update to RFC8445" section, so in order to move the draft forward, I am willing to accept (#18 ) and then leave the Introduction text as it is. I guess one has to assume that the reader of the draft knows ICE well enough to understand when ICE failure etc takes place.

**Comment by juberti** [comment]
> Anyway, I think my issue is clarified in the "Update to RFC8445" section, so in order to move the draft forward, I am willing to accept (#18 ) and then leave the Introduction text as it is. I guess one has to assume that the reader of the draft knows ICE well enough to understand when ICE failure etc takes place.

Right, this is non-normative text, so I think we can keep it simple here and be specific (as we already have done) in the 8445 update section.

**Review by cdh4u — APPROVED** [review]

**Pull request merged**
