### PR TITLE
ICE process failure clarification

### LINKED ISSUE #6: ICE process failure clarification (Editorial/Technical)
Where: Introduction 

What:

Replace:

"If the test for a given pair fails, it is marked accordingly, and if all pairs have failed, the overall
ICE process is considered to have failed."

...with something like:

"If the test for a given pair fails, it is marked accordingly, and if all pairs have failed, the associated checklist is considered to have failed. Once one or more checklists have failed, the ICE agent might consider the ICE process to have failed." 

WHY: The text is misleading, as an ICE agent can declare failure before all pairs have been checked, e.g., if a checklist associated with a stream that is required for the session has failed.

### PR DESCRIPTION
**Pull request by cdh4u**
Fixes #6

### CODE REVIEW

**Review by juberti — CHANGES_REQUESTED** [review]
This seems overly technical for an introduction. Was there a specific thing in this sentence you think needs to be addressed ?

**Comment by cdh4u** [comment]
> This seems overly technical for an introduction. Was there a specific thing in this 
> sentence you think needs to be addressed ?

The original sentence was confusing, and probably wrong.

First it says that if a check fails, it is marked accordingly. So far so good.

But, then it says that if all checks fails, the whole ICE process has failed.

Assuming "all checks" refers to all checks within a check list (since that is what the beginning of the sentence talks about), if all check fails that does not mean the IC process has failed. It is perfectly ok to have a failed check list but still conclude ICE, if the agent considers that the session can be established without the stream associated with the failed check list.

**Comment by juberti** [comment]
In that case I would simply suggest adding the word 'typically', e.g. 'the overall ICE process is typically considered to have failed.'

**Comment by cdh4u** [comment]
> In that case I would simply suggest adding the word 'typically', e.g. 'the overall ICE process 
> is typically considered to have failed.'

That doesn't solve the fact that the sentence is mixing check list state and ICE state. A failed pair has no direct impact on the ICE process. Now the text says that, when all pairs fail, then the ICE process fails.

Also, it is unclear whether "all pairs" refer to all pairs within a check list (that is my assumption) or all pairs within the whole ICE process, so that needs to be clarified anyway.

**Comment by juberti** [comment]
If all pairs in a list fail, ICE typically fails. I don't think that is controversial or confusing.

**Comment by cdh4u** [comment]
> If all pairs in a list fail, ICE typically fails. I don't think that is controversial or confusing.

Is that really true? For example, if I want to establish an audio & video session, and if the checklist associated with the video stream fails, one could still continue with an audio session (assuming the checklist associated with the audio stream succeeds).

But, more important, from an standardization perspective RFC 8445 explicitly talks about concluding ICE successfully even if a checklist fails.

What about the following? It basically says what I want to say, but I managed to make it a little shorter.

 "it is marked accordingly, and if all pairs associated with one or more check lists have failed the ICE agent might consider the ICE process to have failed.

**Comment by cdh4u** [comment]
We could even say "often consider" instead of "might consider", if you want.

**Comment by juberti** [comment]
In an a/v call, if the video stream fails to establish connectivity, the call will typically be terminated. I think this whole discussion of checklists is too detailed for the intro section and wrote up https://github.com/ice-wg/draft-ice-pac/pull/18 as an alternative.

**Comment by cdh4u** [comment]
> In an a/v call, if the video stream fails to establish connectivity, the call will typically be terminated. I >think this whole discussion of checklists is too detailed for the intro section and wrote up #18 as an 
> alternative.

I want to clarify that "if all pairs have failed" is referring to check lists. A reader may think it is referring to all pairs in the whole ICE session. 

All I am asking for is to add  "associated with one or more check lists". I don't think that is too detailed, because the beginning of the sentence already talks about check lists.

**Pull request closed without merging**
