### PR TITLE
Implementing GitHub issue 4

### LINKED ISSUE #4: Use 'ICE candidates' instead of 'candidate addresses' (Editorial)
Where: Introduction

What: s/candidate addresses/ICE candidates

Why: An address is just one part of a candidate

### PR DESCRIPTION
**Pull request by cdh4u**
Fixes #4

### CODE REVIEW

**Review by juberti — CHANGES_REQUESTED** [review]
Feels like a run-on sentence. Let me see if I can come up with something shorter.

**Comment by cdh4u** [comment]
> Feels like a run-on sentence. Let me see if I can come up with something shorter.

Ok.

**Review by juberti — APPROVED** [review]
Reworded, PTAL.

**Comment by cdh4u** [comment]
> Reworded, PTAL.

Looks good.

**Pull request merged**
